parameters:
#    vivait_settings.example.class: Vivait\SettingsBundle\Example

services:
#    vivait_settings.example:
#        class: %vivait_settings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

  vivait_settings.registry:
    class: Vivait\SettingsBundle\Services\SettingsService
    arguments: [@doctrine, @logger, '@vivait_auth.tenant_manager']
    tags:
        - { name: monolog.logger, channel: vivait_settings }